### ISSUE TITLE
Training Equiformer2 with DeNS on a Different Dataset (e.g., ANI-1)

### ISSUE THREAD

**Issue by IliasChair** [atomicarchitects/DeNS#1]
Hello,

Is it possible to train the Equiformer2 model alongside DeNS using a different dataset, such as the ANI-1 dataset? If so, what modifications would be necessary to achieve this?

Any guidance would be greatly appreciated.

Thank you!

**Comment by yilunliao** [comment]
Hi @IliasChair 

Thanks for your interest in this work.
Yes, it should be straightforward to apply DeNS on other datasets.

There are two ways to achieve that:

1. You can see [here](https://github.com/atomicarchitects/equiformer) for a simple implementation on MD17. You can update the dataset and dataloader to use ANI-1 and update the model to be EquiformerV2.

2. If you want to use OCP trainer as in this repo, I think you just need to update dataset/dataloader. Depending on how you train models, you would need to update train function.

I recommend 1. if you are not that familiar since 1. contains everything in the repo without other dependences.

Feel free to ask other concrete questions so that I can provide more guidance.

**Comment by IliasChair** [comment]
Thank you for the prompt response! It's good to know that the approach is feasible.

Given my experience with the OCP repository, I went with option 2. I'm currently in the process of converting the ANI-1x dataset into LMDB databases, split into training, validation, and test sets.

Since I don't have any specific issues or questions at the moment, I'll go ahead and close this issue for now.

Thanks again for your assistance!
